version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: educoins-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: educoins_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: educoins-backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DATABASE_URL=postgresql://postgres:postgrespassword@postgres:5432/educoins_db?schema=public
      - JWT_SECRET=sofia_super_secret_key_123!
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: educoins-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
